#!/bin/bash

sudo mysql -h localhost -e "use football"
                                                                                                                                                                                                                   
#loading players data
datafile="Players.csv"
rows="$(cat $datafile|wc -l)"
rows=$((rows+1))
i=2

while [ "$i" -le "$rows" ];
do
        row="$(cat $datafile | head -n $i | tail -1)"
        _surname="$(echo $row | cut -d ',' -f1)"
        _team="$(echo $row | cut -d ',' -f2)"
        _position="$(echo $row | cut -d ',' -f3)"
        _minutes="$(echo $row | cut -d ',' -f4)"
        _shots="$(echo $row | cut -d ',' -f5)"
        _passes="$(echo $row | cut -d ',' -f6)"
        _tackles="$(echo $row | cut -d ',' -f7)"
        _saves="$(echo $row | cut -d ',' -f8)"

        sudo mysql -h localhost -D "football" -e "INSERT INTO players(surname, team, position, minutes, shots, passes, tackles, saves) VALUES (\"${_surname/\'/''}\", \"${_team/\'/''}\", \"${_position/\'/''}\", $_minutes, $_shots, $_passes, $_tackles, $_saves); "

        i=$(($i+1))

done

#loading teams data
datafile="Teams.csv"
rows="$(cat $datafile|wc -l)"
rows=$(($rows+1))
i=2
while [ "$i" -le "$rows" ];
do

        row="$(cat $datafile | head -n $i | tail -1)"

        _team="$(echo $row | cut -d ',' -f1)"
        _ranking="$(echo $row | cut -d ',' -f2)"
        _games="$(echo $row | cut -d ',' -f3)"
        _wins="$(echo $row | cut -d ',' -f4)"
        _draws="$(echo $row | cut -d ',' -f5)"
        _losses="$(echo $row | cut -d ',' -f6)"
        _goalsFor="$(echo $row | cut -d ',' -f7)"
        _goalsAgainst="$(echo $row | cut -d ',' -f8)"
        _yellowCards="$(echo $row | cut -d ',' -f9)"
        _redCards="$(echo $row | cut -d ',' -f10)"

        sudo mysql -h localhost -D "football" -e "INSERT INTO teams(team, ranking, games, wins, draws, losses, goalsFor, goalsAgainst, yellowCards, redCards) VALUES (\"${_team/\'/''}\", $_ranking, $_games, $_wins, $_draws, $_losses, $_goalsFor, $_goalsAgainst, $_yellowCards, $_redCards); "

        i=$(($i+1))
done
